---
name: Build
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build:production
