name: publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        type: text
        description: Tag name to run from

jobs:
  github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🏗 Setup repo
        if: ${{ !github.event.inputs.tag }}
        uses: actions/checkout@v3

      - name: 🏗 Setup repo from tag
        if: ${{ github.event.inputs.tag }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: 🏗 Setup project
        uses: ./.github/actions/setup-project

      - name: 🎁 Package extension
        run: yarn vsce package --yarn

      - name: 📋 Add package to release
        uses: softprops/action-gh-release@v1
        with:
          files: vscode-expo-*.vsix

  vscode-marketplace:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        if: ${{ !github.event.inputs.tag }}
        uses: actions/checkout@v3

      - name: 🏗 Setup repo from tag
        if: ${{ github.event.inputs.tag }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: 🏗 Setup project
        uses: ./.github/actions/setup-project

      - name: 🚀 Publish to marketplace
        run: yarn vsce publish --yarn
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}

  open-vsx:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        if: ${{ !github.event.inputs.tag }}
        uses: actions/checkout@v3

      - name: 🏗 Setup repo from tag
        if: ${{ github.event.inputs.tag }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: 🏗 Setup project
        uses: ./.github/actions/setup-project

      - name: 🎁 Package extension
        run: yarn vsce package --yarn --out ./vscode-expo.vsix

      - name: 🚀 Publish to open-vsx
        run: npx ovsx publish ./vscode-expo.vsix
        env:
          OVSX_PAT: ${{ secrets.OPENVSX_TOKEN }}
