name: release

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      release:
        description: 'type "release" to create the release (main branch only)'
        required: false

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  dryrun:
    if: ${{ github.ref != 'refs/heads/main' || github.event.inputs.release != 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup project
        uses: ./.github/actions/setup-project

      - name: 📋 Dry-running release
        run: yarn semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish:
    if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.release == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup project
        uses: ./.github/actions/setup-project

      - name: 📋 Release code
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
